version: '3'
services:
  redis:
    image: 'bitnami/redis:6.0'
    container_name: blk-decoder-broker
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  scheduler:
    container_name: blk-decoder-scheduler
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./config/secrets
    volumes: 
      - ${BLOCKSDIR}:${BLOCKSDIR_INTERNAL}
    environment:
    - ENVIRONMENT=${ENVIRONMENT:-dev}
    - CONCURRENCY=${CONCURRENCY:-4}
    - BLOCKSDIR=${BLOCKSDIR}
    command: python -u app.py
  worker:
    container_name: blk-decoder-worker
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: 
      - ./config/secrets
    volumes:
      - ${BLOCKSDIR}:${BLOCKSDIR_INTERNAL}
    environment:
    - ENVIRONMENT=${ENVIRONMENT:-dev}
    - CONCURRENCY=${CONCURRENCY:-4}
    command: celery -A app.celery_app worker -Q BLOCKS --loglevel=DEBUG
